version: '3.1'

services:

  redis:
    image: redis:7.0.8
    restart: unless-stopped
    ports:
      - 6379:6379
  
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
     - "9999:8081"